# Generated by Django 5.1.5 on 2025-01-28 16:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='عنوان مقاله')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='عنوان مقاله')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='عنوان مقاله')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='تصویر مقاله')),
                ('summary', models.TextField(verbose_name='خلاصه مقاله')),
                ('summary_fa', models.TextField(null=True, verbose_name='خلاصه مقاله')),
                ('summary_en', models.TextField(null=True, verbose_name='خلاصه مقاله')),
                ('summary_ar', models.TextField(null=True, verbose_name='خلاصه مقاله')),
                ('content', models.TextField(verbose_name='محتوای مقاله')),
                ('content_fa', models.TextField(null=True, verbose_name='محتوای مقاله')),
                ('content_en', models.TextField(null=True, verbose_name='محتوای مقاله')),
                ('content_ar', models.TextField(null=True, verbose_name='محتوای مقاله')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('location', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('website', models.URLField(verbose_name='وبسایت')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان شرکت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_info/', verbose_name='تصویر شرکت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_en', models.CharField(blank=True, default='Unknown Address', max_length=255)),
                ('address_fa', models.CharField(blank=True, default='Unknown Address', max_length=255)),
                ('address_ar', models.CharField(blank=True, default='Unknown Address', max_length=255)),
                ('phone', models.CharField(default='Unknown', max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='جواب')),
            ],
            options={
                'verbose_name': 'بخش FAQ',
                'verbose_name_plural': 'FAQ section',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_fa', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_fa', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(help_text='Description about the company', verbose_name='About Text')),
                ('about_text_fa', models.TextField(help_text='Description about the company', null=True, verbose_name='About Text')),
                ('about_text_en', models.TextField(help_text='Description about the company', null=True, verbose_name='About Text')),
                ('about_text_ar', models.TextField(help_text='Description about the company', null=True, verbose_name='About Text')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('address_fa', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('address_ar', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('copyright_text', models.CharField(max_length=255, verbose_name='Copyright Text')),
                ('copyright_text_fa', models.CharField(max_length=255, null=True, verbose_name='Copyright Text')),
                ('copyright_text_en', models.CharField(max_length=255, null=True, verbose_name='Copyright Text')),
                ('copyright_text_ar', models.CharField(max_length=255, null=True, verbose_name='Copyright Text')),
            ],
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploaded_pages/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'عربی')], default='fa', max_length=10)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='', max_length=200, verbose_name='عنوان انگلیسی')),
                ('title_en_fa', models.CharField(default='', max_length=200, null=True, verbose_name='عنوان انگلیسی')),
                ('title_en_en', models.CharField(default='', max_length=200, null=True, verbose_name='عنوان انگلیسی')),
                ('title_en_ar', models.CharField(default='', max_length=200, null=True, verbose_name='عنوان انگلیسی')),
                ('title_fa', models.CharField(default='', max_length=200, verbose_name='عنوان فارسی')),
                ('title_fa_fa', models.CharField(default='', max_length=200, null=True, verbose_name='عنوان فارسی')),
                ('title_fa_en', models.CharField(default='', max_length=200, null=True, verbose_name='عنوان فارسی')),
                ('title_fa_ar', models.CharField(default='', max_length=200, null=True, verbose_name='عنوان فارسی')),
                ('title_ar', models.CharField(default='', max_length=200, verbose_name='عنوان عربی')),
                ('title_ar_fa', models.CharField(default='', max_length=200, null=True, verbose_name='عنوان عربی')),
                ('title_ar_en', models.CharField(default='', max_length=200, null=True, verbose_name='عنوان عربی')),
                ('title_ar_ar', models.CharField(default='', max_length=200, null=True, verbose_name='عنوان عربی')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='Steel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description1_en', models.TextField()),
                ('description1_fa', models.TextField(blank=True, null=True)),
                ('description1_ar', models.TextField(blank=True, null=True)),
                ('description2_en', models.TextField(blank=True, null=True)),
                ('description2_fa', models.TextField(blank=True, null=True)),
                ('description2_ar', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='steel_infos/')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(verbose_name='متن فارسی')),
                ('translated_en', models.TextField(blank=True, null=True, verbose_name='ترجمه انگلیسی')),
                ('translated_ar', models.TextField(blank=True, null=True, verbose_name='ترجمه عربی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_fa', models.CharField(max_length=100, null=True, verbose_name='نام')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='نام')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='نام')),
                ('role', models.CharField(max_length=100, verbose_name='نقش')),
                ('role_fa', models.CharField(max_length=100, null=True, verbose_name='نقش')),
                ('role_en', models.CharField(max_length=100, null=True, verbose_name='نقش')),
                ('role_ar', models.CharField(max_length=100, null=True, verbose_name='نقش')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('bio_fa', models.TextField(null=True, verbose_name='بیوگرافی')),
                ('bio_en', models.TextField(null=True, verbose_name='بیوگرافی')),
                ('bio_ar', models.TextField(null=True, verbose_name='بیوگرافی')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='تصویر')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='factory.company', verbose_name='شرکت')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_images/', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='factory.company', verbose_name='شرکت')),
            ],
        ),
    ]
