# Generated by Django 5.1.5 on 2025-01-26 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_article_companyinfo_contactinfo_faq_feature_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=255, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(verbose_name='وبسایت'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.TextField(verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='factory.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='linkedin',
            field=models.URLField(verbose_name='لینکدین'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=100, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='twitter',
            field=models.URLField(verbose_name='توییتر'),
        ),
        migrations.AlterField(
            model_name='image',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='factory.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='company_images/', verbose_name='تصویر'),
        ),
    ]
