# Generated by Django 5.1.5 on 2025-01-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_alter_company_description_alter_company_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteelIndustryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description1', models.TextField(verbose_name='توضیح ۱')),
                ('description2', models.TextField(blank=True, null=True, verbose_name='توضیح ۲')),
                ('description3', models.TextField(blank=True, null=True, verbose_name='توضیح ۳')),
                ('description4', models.TextField(blank=True, null=True, verbose_name='توضیح ۴')),
                ('image', models.ImageField(blank=True, null=True, upload_to='steel_industry/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'اطلاعات صنعت فولاد',
                'verbose_name_plural': 'اطلاعات صنعت فولاد',
            },
        ),
    ]
