# Generated by Django 5.1.5 on 2025-01-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_article_summary_ar_article_summary_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='summary_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary_fa',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_fa',
        ),
    ]
