# Generated by Django 5.1.5 on 2025-01-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_remove_article_summary_ar_remove_article_summary_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary_ar',
            field=models.TextField(null=True, verbose_name='خلاصه مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_en',
            field=models.TextField(null=True, verbose_name='خلاصه مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_fa',
            field=models.TextField(null=True, verbose_name='خلاصه مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان مقاله'),
        ),
    ]
