# Generated by Django 5.1.5 on 2025-01-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_article_summary_ar_article_summary_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steelindustryinfo',
            options={'verbose_name': 'portable slider', 'verbose_name_plural': 'اسلایدر قابل حمل'},
        ),
    ]
