# Generated by Django 5.1.5 on 2025-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_alter_steelindustryinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio_ar',
            field=models.TextField(null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bio_en',
            field=models.TextField(null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bio_fa',
            field=models.TextField(null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='نقش'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_en',
            field=models.CharField(max_length=100, null=True, verbose_name='نقش'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='لینکدین'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='توییتر'),
        ),
    ]
