# Generated by Django 5.1.5 on 2025-01-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_employee_bio_ar_employee_bio_en_employee_bio_fa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'سوال متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات ویژگی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات محصول'),
        ),
    ]
