# Generated by Django 5.1.5 on 2025-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_alter_faq_options_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(default=2, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
