# Generated by Django 5.1.5 on 2025-01-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_navigationlink_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlink',
            name='language',
            field=models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'عربی')], default='fa', max_length=2),
        ),
    ]
