# Generated by Django 5.1.5 on 2025-01-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0014_navigationlink_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlink',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_pages/'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='جواب'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='language',
            field=models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'عربی')], default='fa', max_length=10),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
