# Generated by Django 5.1.5 on 2025-01-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0015_navigationlink_file_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'بخش FAQ', 'verbose_name_plural': 'FAQ section'},
        ),
        migrations.RemoveField(
            model_name='feature',
            name='image',
        ),
    ]
