# Generated by Django 5.1.5 on 2025-01-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0016_alter_faq_options_remove_feature_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steelindustryinfo',
            options={'verbose_name': 'اسلایدر قابل حمل', 'verbose_name_plural': 'portable slider'},
        ),
        migrations.RemoveField(
            model_name='steelindustryinfo',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='steelindustryinfo',
            name='description4',
        ),
    ]
