# Generated by Django 5.1.5 on 2025-01-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0018_alter_product_options_remove_product_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='product',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
    ]
