# Generated by Django 5.1.5 on 2025-01-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0019_remove_feature_product_remove_slider_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='محتوای مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(null=True, verbose_name='محتوای مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='محتوای مقاله'),
        ),
    ]
