# Generated by Django 5.1.5 on 2025-01-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0020_article_content_ar_article_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField()),
                ('description2', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='steel_infos/')),
            ],
        ),
        migrations.DeleteModel(
            name='SteelIndustryInfo',
        ),
    ]
