# Generated by Django 5.1.5 on 2025-01-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0021_steel_delete_steelindustryinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='google_map_url',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_fa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
