# Generated by Django 5.1.5 on 2025-01-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0022_remove_contactinfo_google_map_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steel',
            old_name='description2',
            new_name='description1_ar',
        ),
        migrations.RenameField(
            model_name='steel',
            old_name='description1',
            new_name='description1_en',
        ),
        migrations.RenameField(
            model_name='steel',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='steel',
            name='description1_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steel',
            name='description2_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steel',
            name='description2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steel',
            name='description2_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steel',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='steel',
            name='title_fa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
