# Generated by Django 5.1.5 on 2025-01-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0023_rename_description2_steel_description1_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان عربی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar_ar',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='عنوان عربی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar_en',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='عنوان عربی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar_fa',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='عنوان عربی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en_ar',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en_en',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en_fa',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان فارسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa_ar',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='عنوان فارسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa_en',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='عنوان فارسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa_fa',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='عنوان فارسی'),
        ),
    ]
