# Generated by Django 5.1.3 on 2024-11-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_otp', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
